notifications:
  email: true
  on_failure: always
  on_success: change
language: java
jdk:
  - oraclejdk8
install:
  - wget --quiet --output-document=/tmp/archive.zip "$CEYLON_DIST"
  - unzip -q /tmp/archive.zip
  - unzip -q $PWD/archive/ceylon/dist/ceylon-1.3.3-SNAPSHOT*.zip
  - export PATH=$PATH:$PWD/ceylon-1.3.3-SNAPSHOT/bin/
  - export CEYLON_HOME=$PWD/ceylon-1.3.3-SNAPSHOT
  - wget --quiet --output-document=/tmp/sdk.zip "$CEYLON_SDK"
  - unzip -q /tmp/sdk.zip
  - mkdir -p $TRAVIS_BUILD_DIR/.ceylon
  - echo -e "\n[repository \"sdk\"]\nurl=$PWD/archive/modules\n[repositories]\nlookup=modules\nlookup=+sdk" >> $TRAVIS_BUILD_DIR/.ceylon/config
  - ceylon --version
script:
  - ceylon compile,compile-js # compile-dart not ready for 1.3.3
  - ceylon test $TEST_MODULE # test-js doesn't work!
env:
  global:
    - CEYLON_DIST="https://ci-ceylon.rhcloud.com/job/ceylon-distribution/lastSuccessfulBuild/artifact/*zip*/archive.zip"
    - CEYLON_SDK="https://ci-ceylon.rhcloud.com/job/ceylon-sdk/lastSuccessfulBuild/artifact/*zip*/archive.zip"
    - TEST_MODULE="test.com.vasileff.ceylon.bitset"

